### ISSUE TITLE
Exec Error

### ISSUE THREAD

**Issue by superyarick** [CMSgov/cms-ars-3.1-moderate-microsoft-windows-server-2019-stig-overlay#2]
Error - 
```Input 'LegalNoticeCaption' with value '["CMS Notice and Consent Banner", "US Department of Health and Human Services Warning Statement"]' does not validate to type 'String'.```

```'LegalNoticeCaption'``` is defined as ```Array``` in this overlay
```
  - name: LegalNoticeCaption
    desc: "Use the default values or add an organization-defined legal notice caption"
    type: Array
    value:
      - "CMS Notice and Consent Banner"
      - "US Department of Health and Human Services Warning Statement"
    profile: microsoft-windows-server-2019-stig-baseline
```

However, defined as ```String``` in the baseline profile.
```
  - name: LegalNoticeCaption
    type: string
    value: "DoD Notice and Consent Banner, US Department of Defense Warning Statement, or a site-defined equivalent."
```

Furthermore, it is used as a ```String``` in the controls of the baseline profile (V-93149.rb)
```
describe registry_key('HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System') do
    it { should have_property 'LegalNoticeCaption' }
  end

  key = registry_key('HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System').LegalNoticeCaption.to_s
  legal_notice_caption = input('LegalNoticeCaption')

  describe 'The required legal notice caption' do
    subject { key.scan(/[\w().;,!]/).join }
    it { should cmp legal_notice_caption.scan(/[\w().;,!]/).join }
  end
```
